
[env]
TERM = "xterm-256color"

[window]
# padding = { x = 10, y = 10 }
decorations = "Buttonless"
startup_mode = "SimpleFullscreen" # "Maximized"
option_as_alt = "Both"

[font]
normal = { family = "MesloLGS Nerd Font", style = "Regular" }
bold = { family = "MesloLGS Nerd Font", style = "Bold" }
italic = { family = "MesloLGS Nerd Font", style = "Italic" }
bold_italic = { family = "MesloLGS Nerd Font", style = "Bold Italic" }
size = 14

[general]
import = ["~/.config/alacritty/themes/dracula.toml"]
